"""Add missing fields to Experience models

Revision ID: 185457ff330e
Revises: ac89d8d1cf3e
Create Date: 2025-04-28 13:06:03.457328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '185457ff330e'
down_revision: Union[str, None] = 'ac89d8d1cf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.drop_column('categories', 'type')
    op.drop_index('ix_category_types_code', table_name='category_types')
    op.create_index(op.f('ix_category_types_code'), 'category_types', ['code'], unique=False)
    op.alter_column('experiences', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('languages', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('languages', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_languages_name', table_name='languages')
    op.create_foreign_key(None, 'languages', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'languages', 'users', ['updated_by'], ['id'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'created_by')
    op.drop_column('roles', 'updated_by')
    op.drop_index('ix_skill_types_code', table_name='skill_types')
    op.create_index(op.f('ix_skill_types_code'), 'skill_types', ['code'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_skill_types_code'), table_name='skill_types')
    op.create_index('ix_skill_types_code', 'skill_types', ['code'], unique=True)
    op.add_column('roles', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.create_index('ix_languages_name', 'languages', ['name'], unique=True)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('languages', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('languages', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('languages', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('experiences', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_category_types_code'), table_name='category_types')
    op.create_index('ix_category_types_code', 'category_types', ['code'], unique=True)
    op.add_column('categories', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('categories', 'type_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
