"""Add is_route field to portfolio_links table

Revision ID: 481594d84e06
Revises: e34a0d33eb57
Create Date: 2025-11-03 18:26:04.450223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481594d84e06'
down_revision: Union[str, None] = 'e34a0d33eb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('portfolio_links', sa.Column('is_route', sa.Boolean(), nullable=True))
    # Set default value for existing rows (False for external URLs)
    op.execute('UPDATE portfolio_links SET is_route = FALSE WHERE is_route IS NULL')
    # Now make it NOT NULL
    op.alter_column('portfolio_links', 'is_route', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_links', 'is_route')
    # ### end Alembic commands ###
