"""Add project_date field to projects table

Revision ID: c776336f2e2d
Revises: d79f10af21da
Create Date: 2025-10-29 14:07:27.693932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c776336f2e2d'
down_revision: Union[str, None] = 'd79f10af21da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the project_date column - removed other schema drift changes
    op.add_column('projects', sa.Column('project_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove the project_date column - removed other schema drift changes
    op.drop_column('projects', 'project_date')
    # ### end Alembic commands ###
