"""Add display_style to sections

Revision ID: c8c2653e4157
Revises: 51cad78c6f6e
Create Date: 2025-11-02 16:37:21.200640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8c2653e4157'
down_revision: Union[str, None] = '51cad78c6f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add display_style column to sections table
    op.add_column('sections', sa.Column('display_style', sa.String(), nullable=True, server_default='bordered'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'display_style')
    # ### end Alembic commands ###
