"""Add link management tables for portfolio links with categories and types

Revision ID: e34a0d33eb57
Revises: a23841bd6e30
Create Date: 2025-11-03 14:17:09.996102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e34a0d33eb57'
down_revision: Union[str, None] = 'a23841bd6e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_category_types',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_link_category_types_code'), 'link_category_types', ['code'], unique=False)
    op.create_index(op.f('ix_link_category_types_name'), 'link_category_types', ['name'], unique=False)
    op.create_index('ix_link_category_types_name_code', 'link_category_types', ['name', 'code'], unique=False)
    op.create_table('link_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_code', sa.String(length=5), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_code'], ['link_category_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_categories_code'), 'link_categories', ['code'], unique=True)
    op.create_index(op.f('ix_link_categories_id'), 'link_categories', ['id'], unique=False)
    op.create_index(op.f('ix_link_categories_type_code'), 'link_categories', ['type_code'], unique=False)
    op.create_index('ix_link_categories_type_code_code', 'link_categories', ['type_code', 'code'], unique=False)
    op.create_table('link_category_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['link_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_id', name='uq_link_category_texts_category_language')
    )
    op.create_index('ix_link_category_texts_category_id', 'link_category_texts', ['category_id'], unique=False)
    op.create_index('ix_link_category_texts_category_language', 'link_category_texts', ['category_id', 'language_id'], unique=True)
    op.create_index(op.f('ix_link_category_texts_id'), 'link_category_texts', ['id'], unique=False)
    op.create_index('ix_link_category_texts_language_id', 'link_category_texts', ['language_id'], unique=False)
    op.create_table('portfolio_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['link_categories.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_links_category_id', 'portfolio_links', ['category_id'], unique=False)
    op.create_index(op.f('ix_portfolio_links_id'), 'portfolio_links', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_links_portfolio_id'), 'portfolio_links', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_links_portfolio_id_order', 'portfolio_links', ['portfolio_id', 'order'], unique=False)
    op.create_table('portfolio_link_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['portfolio_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id', 'language_id', name='uq_portfolio_link_texts_link_language')
    )
    op.create_index(op.f('ix_portfolio_link_texts_id'), 'portfolio_link_texts', ['id'], unique=False)
    op.create_index('ix_portfolio_link_texts_language_id', 'portfolio_link_texts', ['language_id'], unique=False)
    op.create_index('ix_portfolio_link_texts_link_id', 'portfolio_link_texts', ['link_id'], unique=False)
    op.create_index('ix_portfolio_link_texts_link_language', 'portfolio_link_texts', ['link_id', 'language_id'], unique=True)
    op.drop_table('rag_embedding')
    op.drop_index(op.f('idx_rag_dead_letter_created'), table_name='rag_dead_letter')
    op.drop_table('rag_dead_letter')
    op.drop_table('rag_index_status')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_expires_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_rag_chunk_source'), table_name='rag_chunk')
    op.drop_index(op.f('idx_rag_chunk_tenant'), table_name='rag_chunk')
    op.drop_index(op.f('idx_rag_chunk_tsv'), table_name='rag_chunk', postgresql_using='gin')
    op.drop_index(op.f('idx_rag_chunk_visibility'), table_name='rag_chunk')
    op.drop_table('rag_chunk')
    op.alter_column('agent_credentials', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_credentials_id'), 'agent_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_id'), 'agent_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('ux_agent_templates_agent_id_name'), 'agent_templates', type_='unique')
    op.create_index(op.f('ix_agent_templates_id'), 'agent_templates', ['id'], unique=False)
    op.create_index(op.f('ix_agent_test_runs_id'), 'agent_test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.drop_index(op.f('ix_portfolio_attachments_language_id'), table_name='portfolio_attachments')
    op.drop_index(op.f('ix_portfolio_attachments_portfolio_id_is_default'), table_name='portfolio_attachments')
    op.drop_constraint(op.f('fk_portfolio_attachments_language_id'), 'portfolio_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_attachments', 'languages', ['language_id'], ['id'])
    op.drop_constraint(op.f('fk_portfolio_images_language_id'), 'portfolio_images', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_images', 'languages', ['language_id'], ['id'])
    op.drop_index(op.f('idx_single_default_portfolio'), table_name='portfolios', postgresql_where='(is_default = true)')
    op.create_index(op.f('ix_portfolios_is_default'), 'portfolios', ['is_default'], unique=False)
    op.drop_constraint(op.f('section_texts_section_id_fkey'), 'section_texts', type_='foreignkey')
    op.create_foreign_key(None, 'section_texts', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.drop_constraint(None, 'section_texts', type_='foreignkey')
    op.create_foreign_key(op.f('section_texts_section_id_fkey'), 'section_texts', 'sections', ['section_id'], ['id'])
    op.drop_index(op.f('ix_portfolios_is_default'), table_name='portfolios')
    op.create_index(op.f('idx_single_default_portfolio'), 'portfolios', ['is_default'], unique=True, postgresql_where='(is_default = true)')
    op.drop_constraint(None, 'portfolio_images', type_='foreignkey')
    op.create_foreign_key(op.f('fk_portfolio_images_language_id'), 'portfolio_images', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'portfolio_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_portfolio_attachments_language_id'), 'portfolio_attachments', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_portfolio_attachments_portfolio_id_is_default'), 'portfolio_attachments', ['portfolio_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_portfolio_attachments_language_id'), 'portfolio_attachments', ['language_id'], unique=False)
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agent_test_runs_id'), table_name='agent_test_runs')
    op.drop_index(op.f('ix_agent_templates_id'), table_name='agent_templates')
    op.create_unique_constraint(op.f('ux_agent_templates_agent_id_name'), 'agent_templates', ['agent_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agent_sessions_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_credentials_id'), table_name='agent_credentials')
    op.alter_column('agent_credentials', 'api_key_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('rag_chunk',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('rag_chunk_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_uri', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modality', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('part_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checksum', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, COALESCE(text, ''::text))", persisted=True), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.TEXT(), server_default=sa.text("'public'::text"), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.TEXT(), server_default=sa.text("'default'::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rag_chunk_pkey'),
    sa.UniqueConstraint('source_table', 'source_id', 'source_field', 'part_index', 'version', name='uq_rag_chunk_logical', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_rag_chunk_visibility'), 'rag_chunk', ['visibility'], unique=False)
    op.create_index(op.f('idx_rag_chunk_tsv'), 'rag_chunk', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_rag_chunk_tenant'), 'rag_chunk', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_rag_chunk_source'), 'rag_chunk', ['source_table', 'source_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('success', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('record_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('previous_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('retention_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_event'), 'audit_logs', ['user_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_created'), 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_expires_at'), 'audit_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_category'), 'audit_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_event'), 'audit_logs', ['created_at', 'event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_category_severity'), 'audit_logs', ['event_category', 'severity'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('rag_index_status',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_indexed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_index_status_pkey')),
    sa.UniqueConstraint('source_table', 'source_id', name=op.f('uq_rag_index_status_src'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('rag_dead_letter',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_table', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_dead_letter_pkey'))
    )
    op.create_index(op.f('idx_rag_dead_letter_created'), 'rag_dead_letter', ['created_at'], unique=False)
    op.create_table('rag_embedding',
    sa.Column('chunk_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('modality', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dim', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding_vec', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['rag_chunk.id'], name=op.f('rag_embedding_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'model', 'modality', name=op.f('rag_embedding_pkey'))
    )
    op.drop_index('ix_portfolio_link_texts_link_language', table_name='portfolio_link_texts')
    op.drop_index('ix_portfolio_link_texts_link_id', table_name='portfolio_link_texts')
    op.drop_index('ix_portfolio_link_texts_language_id', table_name='portfolio_link_texts')
    op.drop_index(op.f('ix_portfolio_link_texts_id'), table_name='portfolio_link_texts')
    op.drop_table('portfolio_link_texts')
    op.drop_index('ix_portfolio_links_portfolio_id_order', table_name='portfolio_links')
    op.drop_index(op.f('ix_portfolio_links_portfolio_id'), table_name='portfolio_links')
    op.drop_index(op.f('ix_portfolio_links_id'), table_name='portfolio_links')
    op.drop_index('ix_portfolio_links_category_id', table_name='portfolio_links')
    op.drop_table('portfolio_links')
    op.drop_index('ix_link_category_texts_language_id', table_name='link_category_texts')
    op.drop_index(op.f('ix_link_category_texts_id'), table_name='link_category_texts')
    op.drop_index('ix_link_category_texts_category_language', table_name='link_category_texts')
    op.drop_index('ix_link_category_texts_category_id', table_name='link_category_texts')
    op.drop_table('link_category_texts')
    op.drop_index('ix_link_categories_type_code_code', table_name='link_categories')
    op.drop_index(op.f('ix_link_categories_type_code'), table_name='link_categories')
    op.drop_index(op.f('ix_link_categories_id'), table_name='link_categories')
    op.drop_index(op.f('ix_link_categories_code'), table_name='link_categories')
    op.drop_table('link_categories')
    op.drop_index('ix_link_category_types_name_code', table_name='link_category_types')
    op.drop_index(op.f('ix_link_category_types_name'), table_name='link_category_types')
    op.drop_index(op.f('ix_link_category_types_code'), table_name='link_category_types')
    op.drop_table('link_category_types')
    # ### end Alembic commands ###
