"""Add file_name to portfolio_images table

Revision ID: f173da99a68e
Revises: d9b8a86b83db
Create Date: 2025-07-02 16:51:07.855075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f173da99a68e'
down_revision: Union[str, None] = 'd9b8a86b83db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('portfolio_images', sa.Column('file_name', sa.String(), nullable=True))
    
    # Update existing records to extract filename from image_path
    op.execute("""
        UPDATE portfolio_images 
        SET file_name = COALESCE(
            REVERSE(SPLIT_PART(REVERSE(image_path), '/', 1)),
            'unknown.png'
        )
        WHERE file_name IS NULL
    """)
    
    # Then make the column NOT NULL
    op.alter_column('portfolio_images', 'file_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_images', 'file_name')
    # ### end Alembic commands ###
